[build]
functions = "lambda-functions"
publish = "dist"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/app/blog/:splat"
  status = 200
  force = true

[[redirects]]
from = "/"
to = "/.netlify/functions/app"

[context.production]
  environment = { NODE_VERSION = "12.16.1" }
