[build]
functions = "lambda-functions"
publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/"
  force = true

[context.production]
  environment = { NODE_VERSION = "12.16.1" }
