[build]
functions = "lambda-functions"
publish = "dist"

[[redirects]]
from = "/dist/*"
to = "/dist/:splat"
status = 200
force = true
    
[[redirects]]
from = "/*"
to = "/.netlify/functions/app/"
status = 200
force = false

[context.production]
  environment = { NODE_VERSION = "12.16.1" }
