[build]
functions = "lambda-functions"
publish = "dist"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/app/blog/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/app/"
  status = 200

[context.production]
  environment = { NODE_VERSION = "12.16.1" }
