[build]
functions = "lambda-functions"
publish = "dist"

[[redirects]]
  from = "/app/"
  to = "/.netlify/functions/app/"
  status = 200

[context.production]
  environment = { NODE_VERSION = "12.16.1" }
